# This is a basic workflow to help you get started with Actions

name: Update Profile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Make Request
        id: myRequest
        uses: satak/webrequest-action@master
        with:
          url: "https://uselessfacts.jsph.pl/today.json?language=en"
          method: GET
      - name: Save Response
        run: $output = '${{ steps.myRequest.outputs.output }}'
      - name: Show Details
        run: echo $($output.statusCode)
