# This is a basic workflow to help you get started with Actions

name: Update Profile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetch data
        run: curl "https://uselessfacts.jsph.pl/today.json?language=en" -o data.json 
      - name: Parse data
        id: parse_data
        run: echo '::set-output name=text::'$(jq -r '.text' data.json)
      - name: Show data
        run: echo ${{ steps.parse_data.outputs.text }}
      - name: Run script file
        uses: actions/setup-node@v3
      - run: npm run update
